import './style.css';
import { createWorld } from './scene.js';
import { questions, tiers, getQuestions, getProfile, calculateResult } from './quiz.js';
import { buildReport, compareResults } from './reports.js';
import { createStore } from './storage.js';
import { createAccessClient, premiumFeatures } from './access.js';
import { icons } from './icons.js';
import { getCardCopy } from './export-copy.js';

const store = createStore({getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)});
const accessClient = createAccessClient();
const access = await accessClient.getAccess();
const dims = ['EI','SN','TF','JP'];
const names = ['能量矩阵','灵感幻境','共鸣网络','秩序之城'];
const subs = ['连接世界的方式','感知信息的频率','做出决定的底色','展开生活的节奏'];
const colors = ['#caff48','#ad87ff','#ff77b7','#69e6ff'];
const ico = ['globe','spark','heart','grid'];
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatDate = value => new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
let tierId=store.snapshot().selectedTier, screen='home', answers=[], index=0, selected=null, activeIsland=0, record=null, audio, sound=false;
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches, toastTimer, comparisonIds=[], reportTab='insights';
const tier=()=>tiers.find(t=>t.id===tierId), items=()=>getQuestions(tierId);
const app=document.querySelector('#app');
app.innerHTML=`<div class="site-shell"><header><a class="brand" href="#" aria-label="人格宇宙首页"><span class="brand-symbol">✳</span><span>INNER<span class="brand-light">SPACE</span><small>人格宇宙<span class="version">2.0</span></small></span></a><nav aria-label="主导航"><button class="nav-link active" data-action="home">探索宇宙</button><button class="nav-link" data-action="atlas">人格图鉴 <sup>16</sup></button><button class="nav-link" data-action="history">成长档案</button><button class="nav-link pro-nav" data-action="pro">SPACE PRO ${icons.up}</button></nav><div class="header-tools"><span class="connection"><i></i> SYSTEM ONLINE</span><button class="icon-button" id="sound" aria-label="开启音效" aria-pressed="false">${icons.mute}</button><button class="icon-button help-button" data-action="guide" aria-label="探索指南">${icons.help}</button></div></header>
<main><section class="hero"><div class="copy" id="content"></div><div class="universe"><div class="scene-corner top-left"></div><div class="scene-corner bottom-right"></div><div class="scene-status"><span><i></i> INNER UNIVERSE</span><b>LIVE / 3D</b></div><div class="scene-grid"></div><div id="world" role="img" aria-label="可拖动旋转、点击探索的赛博人格宇宙"></div><span class="scene-coordinate">X 024.8<br>Y 016.0<br>Z ∞</span><div class="scene-tag"><span class="mini-cross">+</span> YOUR MIND. YOUR WORLD.</div><div class="drag-tip">${icons.rotate} 拖动旋转 · 点击岛屿探索 <button class="small-icon" data-action="motion" aria-label="${reduced?'播放场景动画':'暂停场景动画'}">${reduced?'▷':'Ⅱ'}</button></div><span class="scene-no">UNIVERSE_001</span></div></section>
<div id="workspace"></div><section class="journey"><div class="section-heading"><div><span class="overline">// YOUR EXPLORATION MAP</span><h2>四个维度，无限种你。<span>4 SECTORS / 16 PERSONALITIES</span></h2></div><span class="journey-counter">01 <span>/ 04</span></span></div><div class="world-cards"></div></section><section class="pro-strip"><div class="pro-strip-heading"><span class="pro-badge">SPACE PRO</span><h2>解码之后，继续进化。</h2><p>把一个人格结果，变成一份属于你的成长路线。</p><button class="text-button" data-action="pro">探索高级能力 ${icons.up}</button></div><button class="feature-tile" data-action="report"><span>01 / DEEP INSIGHTS</span>${icons.spark}<h3>深度人格报告</h3><p>优势、盲区、工作与关系偏好</p><b>体验报告 ${icons.arrow}</b></button><button class="feature-tile" data-action="growth"><span>02 / GROWTH PLAN</span>${icons.grid}<h3>7 日成长计划</h3><p>每天一个小行动，探索另一面</p><b>查看计划 ${icons.arrow}</b></button><button class="feature-tile" data-action="history"><span>03 / PERSONAL TIMELINE</span>${icons.globe}<h3>记录你的变化</h3><p>回看历史，对比四维选择倾向</p><b>进入档案 ${icons.arrow}</b></button></section>
<footer><span><i></i> STAY CURIOUS. STAY YOU.</span><span>人格是坐标，不是边界。</span><button data-action="guide">探索须知 ${icons.up}</button></footer></main></div><dialog id="dialog"><div id="dialog-content"></div></dialog><div id="toast" role="status" aria-live="polite"></div>`;
let world;
try {world=createWorld(document.querySelector('#world'),{onSelect:i=>{activeIsland=i;world.select(i);renderCards();toast(`SECTOR 0${i+1} · ${names[i]} / ${subs[i]}`);}});world.setReducedMotion(reduced);world.select(0);}catch{document.querySelector('#world').innerHTML='<div class="canvas-error">3D 信号暂未连接<small>你的浏览器无法显示场景，情境探索仍然可用。</small></div>';}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3300);}
function chime(f=470){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*1.4,audio.currentTime+.13);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.27);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.29);}catch{}}
function scrollTop(){window.scrollTo({top:0,behavior:'instant'});}
function focusContent(){document.querySelector('.question-title,.result-type,.page-title')?.focus({preventScroll:true});}
function saveDraft(){store.saveDraft(tierId,answers,index);if(!store.available)toast('当前环境无法持久保存，进度仅在本次页面中保留。');}
function loadDraft(){const d=store.snapshot().drafts[tierId];answers=d?[...d.answers]:[];index=d?.index||0;selected=answers[index]===undefined?null:items()[index].options.findIndex(o=>o.value===answers[index]);}
function resultOf(r){return calculateResult(r.answers,getQuestions(r.tierId));}
function latestRecord(){return store.snapshot().history[0]||null;}
function demoRecord(){return {id:'demo',tierId:'quick',createdAt:new Date().toISOString(),growthDone:[],answers:questions.map(q=>'ENFP'.includes(q.dimension[0])?q.dimension[0]:q.dimension[1])};}
function currentRecord(){return store.snapshot().history.find(r=>r.id===record?.id)||record||latestRecord()||demoRecord();}
function go(screenName){screen=screenName;render();scrollTop();focusContent();}
function renderCards(){const chapter=tier().count/4;const progress=screen==='home'?(store.snapshot().drafts[tierId]?.answers.length||0):answers.length;document.querySelector('.world-cards').innerHTML=names.map((name,i)=>`<button class="world-card ${i===activeIsland?'selected':''}" style="--sector:${colors[i]}" data-island="${i}" aria-pressed="${i===activeIsland}"><div class="card-top"><span>${icons[ico[i]]}</span><span class="card-number">SECTOR_0${i+1}</span><b>${dims[i][0]} / ${dims[i][1]}</b></div><div class="card-bottom"><div><h3>${name}</h3><p>${subs[i]}</p></div>${progress>=(i+1)*chapter?icons.check:icons.up}</div><div class="card-progress" style="width:${Math.min(1,Math.max(0,progress-i*chapter)/chapter)*100}%"></div></button>`).join('');document.querySelector('.journey-counter').innerHTML=`0${activeIsland+1} <span>/ 04</span>`;}
function modeMarkup(){return tiers.map((t,i)=>`<button class="mode-card ${t.id===tierId?'selected':''}" data-tier="${t.id}" aria-pressed="${t.id===tierId}"><span class="mode-top">${['QUICK','STANDARD','DEEP'][i]}<i>${t.id===tierId?'●':'○'}</i></span><strong>${t.count}<small>题</small></strong><span class="mode-name">${t.name}</span><span class="mode-time">约 ${t.minutes} 分钟${store.snapshot().drafts[t.id]?.answers.length?' · 已存档':''}</span></button>`).join('');}
function traitsMarkup(r){return r.percentages.map((p,i)=>`<div class="trait"><div class="trait-label"><span>${subs[i]}</span><b>${p.leftPercent===50?'均衡 / 50 : 50':`${p.leftPercent>50?p.left:p.right} · ${Math.max(p.leftPercent,100-p.leftPercent)}%`}</b></div><div class="trait-track"><span>${p.left}</span><div><i style="width:${p.leftPercent}%;background:${colors[i]}"></i></div><span>${p.right}</span></div></div>`).join('');}
function render(){document.body.dataset.screen=screen;document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.action===screen||(screen==='quiz'&&b.dataset.action==='home')));const el=document.querySelector('#content');
 if(screen==='home'){const d=store.snapshot().drafts[tierId];el.innerHTML=`<div class="eyebrow"><span></span> PERSONALITY EXPLORATION / 2026</div><h1>你，远不止<br><span>四个字母。</span><sup>✳</sup></h1><p class="hero-description">进入你的赛博人格宇宙。<br>让每一次选择，点亮一个未知的自己。</p><div class="mode-label"><span>选择你的探索深度</span><small>SELECT YOUR MODE</small></div><div class="mode-grid">${modeMarkup()}</div><button class="primary start-button" data-action="start"><span>${d?.answers.length?'继续解码':'开启人格扫描'}</span>${icons.arrow}</button><div class="hero-meta"><span>${icons.clock} ${tier().count} 个情境 · 约 ${tier().minutes} 分钟</span><span>${icons.lock} 无需登录 · 本机保存</span></div><div class="hero-footnote"><span class="tiny-orbit">◎</span> 16 种人格。无限种可能。<button data-action="guide">不被标签定义 ${icons.up}</button></div>`;}
 if(screen==='quiz'){const qs=items(),q=qs[index],chapter=qs.length/4;activeIsland=Math.floor(index/chapter);world?.select(activeIsland);world?.setProgress?.(answers.length,qs.length);el.innerHTML=`<div class="quiz-top"><button class="text-button" data-action="exit">${icons.back} 保存并退出</button><span>${tier().name} <b>${String(index+1).padStart(2,'0')}</b> / ${qs.length}</span></div><div class="progress-track"><i style="width:${index/qs.length*100}%"></i></div><div class="eyebrow quiz-eyebrow" style="color:${colors[activeIsland]}">${icons[ico[activeIsland]]} ${names[activeIsland]}<span>SECTOR_0${activeIsland+1}</span></div><h1 class="question-title" tabindex="-1">${q.title}</h1><p class="question-description">${q.description}</p><div class="options">${q.options.map((o,i)=>`<button class="option ${selected===i?'chosen':''}" data-option="${i}" aria-pressed="${selected===i}"><span class="option-letter">${String.fromCharCode(65+i)}</span><span><b>${o.text}</b><small>${o.detail}</small></span><span class="option-check">${selected===i?icons.check:icons.up}</span></button>`).join('')}</div><div class="quiz-actions"><button class="text-button" data-action="back" ${index===0?'disabled':''}>${icons.back} 上一题</button><button class="primary" data-action="next" ${selected===null?'disabled':''}>${index===qs.length-1?'生成人格档案':'确认并继续'} ${icons.arrow}</button></div><p class="gentle-note">没有标准答案。选择更贴近日常的你，不必追求“理想答案”。</p>`;}
 if(screen==='result'){const r=resultOf(record);el.innerHTML=`<div class="eyebrow">${icons.spark} DECODE COMPLETE / 解码完成</div><div class="result-topline"><h1 class="result-type" tabindex="-1">${r.type}</h1><span>${tier().count} QUESTIONS<br>PERSONALITY ID</span></div><h2 class="result-name">${r.name}</h2><p class="result-description">${r.description}</p>${r.provisional?`<p class="tie-note">${r.tieDimensions.join(' / ')} 维度选择均衡，当前类型仅为临时参考。</p>`:''}<div class="tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="traits">${traitsMarkup(r)}</div><div class="result-actions"><button class="primary" data-action="report">查看深度报告 ${icons.up}</button><button class="secondary" data-action="download" aria-label="下载人格卡">${icons.download}</button><button class="text-button" data-action="restart">重新探索 ${icons.rotate}</button></div><p class="gentle-note">本轮选择倾向 · 已保存到成长档案 · 不构成心理诊断</p>`;}
 if(screen==='report')renderReport();else if(screen==='history')renderHistory();else document.querySelector('#workspace').innerHTML='';
 renderCards();
}
function start(){loadDraft();screen='quiz';chime();render();scrollTop();focusContent();}
function showReport(tab='insights',id){if(id)record=store.snapshot().history.find(r=>r.id===id)||null;else record=currentRecord();reportTab=tab;go('report');}
function radar(r){const values=r.percentages.map(p=>p.leftPercent/100),pts=values.map((v,i)=>{const a=i*Math.PI/2-Math.PI/2;return `${150+Math.cos(a)*(v*107)},${145+Math.sin(a)*(v*107)}`}).join(' ');return `<svg class="radar" viewBox="0 0 300 290" role="img" aria-label="四维左侧偏好比例，轴为 E、S、T、J，外圈为百分之百"><g fill="none" stroke="#293346">${[.25,.5,.75,1].map(v=>`<path d="M150 ${145-v*107} L${150+v*107} 145 L150 ${145+v*107} L${150-v*107} 145Z"/>`).join('')}<path d="M150 38v214M43 145h214"/></g><polygon points="${pts}" fill="#caff4825" stroke="#caff48" stroke-width="2"/><g fill="#caff48">${values.map((v,i)=>{const a=i*Math.PI/2-Math.PI/2;return `<circle cx="${150+Math.cos(a)*(v*107)}" cy="${145+Math.sin(a)*(v*107)}" r="4"/>`;}).join('')}</g><g fill="#a7b2c7" font-size="11" text-anchor="middle"><text x="150" y="20">E · 外向</text><text x="274" y="149">S</text><text x="150" y="279">T · 思考</text><text x="25" y="149">J</text></g></svg>`;}
function reportSections(report){return `<div class="report-columns"><section class="report-box"><span class="overline">01 / YOUR SUPERPOWERS</span><h3>你的优势倾向</h3>${report.strengths.map(x=>`<div class="insight"><h4>${x.title}</h4><p>${x.body}</p></div>`).join('')}</section><section class="report-box"><span class="overline">02 / ROOM TO GROW</span><h3>可以留意的另一面</h3>${report.blindSpots.map(x=>`<div class="insight"><h4>${x.title}</h4><p>${x.body}</p></div>`).join('')}</section></div><div class="report-columns"><section class="report-box accent-purple"><span class="overline">03 / WORK STYLE</span><h3>${report.work.title}</h3><p>${report.work.body}</p></section><section class="report-box accent-cyan"><span class="overline">04 / CONNECTIONS</span><h3>${report.relationships.title}</h3><p>${report.relationships.body}</p></section></div>`;}
function renderReport(){record=currentRecord();const r=resultOf(record),report=buildReport(r),isDemo=record.id==='demo',done=record.growthDone||[];document.querySelector('#workspace').innerHTML=`<div class="page-heading"><div><span class="overline">SPACE PRO / PERSONAL DOSSIER</span><h1 class="page-title" tabindex="-1">你的内在宇宙，<span>完整展开。</span></h1><p>${isDemo?'当前是 ENFP 示例报告。完成探索后，生成属于你的内容。':`${getQuestions(record.tierId).length} 题 · ${formatDate(record.createdAt)} · 基于本轮选择生成`}</p></div><div class="page-actions"><button class="secondary" data-action="home">${icons.back} 返回宇宙</button><button class="primary" data-action="export-report">导出完整报告 ${icons.download}</button></div></div><div class="report-summary"><div class="report-identity"><span class="pro-badge">${isDemo?'示例预览':'PRO 体验开放'}</span><strong>${r.type}</strong><h2>${r.name}</h2><p>${report.summary}</p>${r.provisional?`<p class="tie-note">${r.tieDimensions.join(' / ')} 维度均衡。请以维度描述为主，类型仅供临时参考。</p>`:''}<div class="tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="report-radar">${radar(r)}<small>左侧偏好占比 · 非能力评分</small></div><div class="report-fingerprint"><span class="overline">PERSONALITY FINGERPRINT</span><div class="traits">${traitsMarkup(r)}</div></div></div><div class="report-tabs" role="tablist" aria-label="报告内容"><button role="tab" aria-selected="${reportTab==='insights'}" data-report-tab="insights">人格解码</button><button role="tab" aria-selected="${reportTab==='growth'}" data-report-tab="growth">7 日成长计划 <span>${done.length}/7</span></button></div><div role="tabpanel">${reportTab==='insights'?reportSections(report):`<div class="growth-intro"><div><h2>改变，从一个小行动开始。</h2><p>按自己的节奏完成，不必连续打卡。${isDemo?'示例打卡不会写入你的档案。':'完成状态保存在这份报告中。'}</p></div><span>${done.length}<small> / 7 已完成</small></span></div><div class="growth-list">${report.growthPlan.map(d=>`<button class="growth-item ${done.includes(d.day)?'done':''}" data-growth="${d.day}" aria-pressed="${done.includes(d.day)}"><span class="day-number">DAY ${String(d.day).padStart(2,'0')}</span><span><b>${d.title}</b><small>${d.body}</small></span><span class="day-check">${done.includes(d.day)?icons.check:'+'}</span></button>`).join('')}</div>`}</div><p class="report-disclaimer">本报告根据本轮选择与预设内容规则生成，未经心理测量验证。题量更多意味着情境覆盖更广，不等同于更高的测量准确度。人格会随情境变化，所有建议仅供自我观察。</p>`;}
function renderHistory(){const history=store.snapshot().history;comparisonIds=comparisonIds.filter(id=>history.some(r=>r.id===id));if(comparisonIds.length<2&&history.length>=2)comparisonIds=[history[1].id,history[0].id];const records=comparisonIds.map(id=>history.find(r=>r.id===id));document.querySelector('#workspace').innerHTML=`<div class="page-heading"><div><span class="overline">YOUR PERSONAL TIMELINE</span><h1 class="page-title" tabindex="-1">你一直在变，<span>值得被看见。</span></h1><p>最多保存最近 30 次探索。记录仅在当前浏览器中保存。</p></div><button class="primary" data-action="home">开启新的探索 ${icons.arrow}</button></div>${history.length?`<div class="history-layout"><div class="history-list">${history.map(r=>{const p=resultOf(r);return `<article class="history-item"><div><b>${p.type}${p.provisional?'*':''}</b><span>${p.provisional?'维度均衡 · 临时类型':p.name}</span></div><div><small>${formatDate(r.createdAt)}</small><span>${getQuestions(r.tierId).length} 题 · 成长 ${r.growthDone.length}/7</span></div><button class="text-button" data-record="${r.id}">查看报告 ${icons.up}</button><button class="icon-button delete-record" data-delete="${r.id}" aria-label="删除 ${formatDate(r.createdAt)} 的记录">${icons.close}</button></article>`;}).join('')}</div><section class="comparison report-box"><span class="overline">SIDE BY SIDE / 变化对比</span><h2>同一个你，不同的时刻。</h2>${history.length>=2?`<div class="comparison-selects">${['起点记录','对比记录'].map((label,i)=>`<label>${label}<select data-compare="${i}">${history.map(r=>`<option value="${r.id}" ${comparisonIds[i]===r.id?'selected':''}>${formatDate(r.createdAt)} · ${resultOf(r).type} · ${getQuestions(r.tierId).length}题</option>`).join('')}</select></label>`).join('')}</div><div class="comparison-legend"><span>● 起点</span><span>● 对比</span></div>${compareResults(resultOf(records[0]),resultOf(records[1])).map((c,i)=>`<div class="compare-row"><div><span>${subs[i]} (${c.left})</span><b>${c.delta>0?'+':''}${c.delta} 个百分点</b></div><div class="compare-bar"><i style="width:${c.before}%"></i><span>${c.before}%</span></div><div class="compare-bar second"><i style="width:${c.after}%"></i><span>${c.after}%</span></div></div>`).join('')}<p class="gentle-note">${records[0].tierId!==records[1].tierId?'两次题量不同，仅作粗略观察。':''}变化表示本次选择比例不同，不代表能力增长或下降。</p>`:`<div class="comparison-empty">${icons.globe}<p>再完成一次探索，<br>即可比较两次四维倾向。</p><button class="text-button" data-action="home">继续探索 ${icons.arrow}</button></div>`}</section></div>`:`<div class="empty-state">${icons.globe}<h2>第一份人格档案，等你点亮。</h2><p>完成任意档位后，结果与成长计划会自动留在这里。</p><button class="primary" data-action="start">开始快速扫描 ${icons.arrow}</button></div>`}`;}
function modal(content){const d=document.querySelector('#dialog');document.querySelector('#dialog-content').innerHTML=`<button class="icon-button dialog-close" data-action="close" aria-label="关闭">${icons.close}</button><div class="modal-inner">${content}</div>`;if(!d.open)d.showModal();}
function guide(){modal(`<span class="overline">WELCOME TO YOUR INNER SPACE</span><h2>先好奇，再定义。</h2><div class="guide-steps"><div><b>01</b><span><strong>选一个探索档位</strong>12 / 32 / 60 题，情境覆盖逐步增加。四个维度始终均衡。</span></div><div><b>02</b><span><strong>跟随日常的自己</strong>没有对错，可以回到前题修改。每档进度独立保存。</span></div><div><b>03</b><span><strong>让理解变成行动</strong>生成报告、收藏人格卡，完成成长计划，回看自己的变化。</span></div></div><p class="modal-note">这是 MBTI 四维偏好启发的自我探索体验，不是官方量表或心理诊断。所有答案与历史只保存在本机。高级功能当前开放体验，尚未开通实际收费。</p><button class="primary" data-action="begin-from-modal">准备好进入宇宙 ${icons.arrow}</button>`);}
function pro(){modal(`<span class="pro-badge">SPACE PRO / 体验开放</span><h2>不止一个类型。<br>是一份自我探索地图。</h2><p>基础探索始终可以直接开始。高级能力已可体验，付费服务尚未启用。</p><div class="pro-features">${premiumFeatures.map(f=>`<div>${icons.check}<span><b>${f.name}</b><small>${f.description}</small></span></div>`).join('')}</div><div class="modal-actions"><button class="primary" data-action="pro-report">体验深度报告 ${icons.up}</button><span class="gentle-note">无需订阅 · 无扣款</span></div>`);}
function atlas(){const types=['INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP'];modal(`<span class="overline">16 PERSONALITY ARCHETYPES</span><h2>找到你的频率。</h2><p>每一种性格都有自己的闪光点。点击解锁不同的人格宇宙。</p><div class="atlas-grid">${types.map((t,i)=>`<button data-type="${t}" class="type-card type-${Math.floor(i/4)}"><b>${t}</b><span>${getProfile(t).name}</span>${icons.up}</button>`).join('')}</div>`);}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function downloadCard(){const r=resultOf(record),copy=getCardCopy(r),c=document.createElement('canvas');c.width=1080;c.height=1440;const x=c.getContext('2d');x.fillStyle='#080c16';x.fillRect(0,0,1080,1440);x.strokeStyle='#1d2934';for(let i=0;i<1080;i+=50){x.beginPath();x.moveTo(i,0);x.lineTo(i,1440);x.stroke();}for(let i=0;i<1440;i+=50){x.beginPath();x.moveTo(0,i);x.lineTo(1080,i);x.stroke();}x.fillStyle='#caff48';x.fillRect(80,130,120,4);x.font='bold 28px sans-serif';x.fillText('INNER SPACE // 人格宇宙',80,95);x.fillStyle='#8895aa';x.font='22px sans-serif';x.fillText('PERSONALITY SCAN / COMPLETE',80,250);x.fillStyle='#caff48';x.font='bold 184px sans-serif';x.fillText(copy.type,70,450);x.fillStyle='#f0f5ff';x.font='bold 60px sans-serif';x.fillText(copy.name,80,565);x.font='28px sans-serif';let line='',y=665;for(const char of copy.description){if(x.measureText(line+char).width>910){x.fillText(line,80,y);line='';y+=47;}line+=char;}x.fillText(line,80,y);r.percentages.forEach((p,i)=>{const yy=875+i*83;x.font='26px sans-serif';x.fillStyle='#9aa8bd';x.fillText(`${p.left} / ${p.right}`,80,yy);x.fillStyle='#262939';x.fillRect(205,yy-21,590,12);x.fillStyle=colors[i];x.fillRect(205,yy-21,590*p.leftPercent/100,12);x.fillText(p.leftPercent===50?'均衡':`${Math.max(p.leftPercent,100-p.leftPercent)}% ${p.leftPercent>50?p.left:p.right}`,835,yy);});x.fillStyle='#d7dfec';x.font='28px sans-serif';x.fillText('人格是坐标，不是边界。',80,1290);x.fillStyle='#7f8ba0';x.font='21px sans-serif';x.fillText(`${getQuestions(record.tierId).length}题 · ${copy.footer}`,80,1350);c.toBlob(blob=>{if(blob){saveBlob(blob,`INNER-SPACE-${r.type}.png`);toast('人格卡已生成，可以保存到设备。');}});}
function exportReport(){const rr=currentRecord(),r=resultOf(rr),rep=buildReport(r);const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${r.type} · 人格探索报告</title><style>body{font-family:system-ui,sans-serif;max-width:850px;margin:40px auto;padding:0 25px;color:#182838;line-height:1.8}h1{font-size:52px;margin:10px 0}h2{margin-top:35px}h3{margin-bottom:3px}p{margin-top:5px}section{break-inside:avoid}small{color:#64748b}.summary{padding:25px;background:#edf4f0}li{margin:10px 0}button{padding:10px 18px;border:1px solid #bbb;background:white;cursor:pointer}@media print{button{display:none}body{margin:0}}</style><body><button onclick="window.print()">打印 / 保存为 PDF</button><p>INNER SPACE // ${rr.id==='demo'?'示例报告':'个人探索报告'}</p><div class="summary"><h1>${r.type} · ${r.name}</h1><p>${rep.summary}</p><small>${getQuestions(rr.tierId).length} 题 / ${formatDate(rr.createdAt)}</small>${r.provisional?`<p>${r.tieDimensions.join(' / ')} 维度均衡，类型仅为临时参考。</p>`:''}</div><h2>四维选择比例</h2>${r.percentages.map((p,i)=>`<p>${subs[i]}：${p.left} ${p.leftPercent}% / ${p.right} ${100-p.leftPercent}%</p>`).join('')}<h2>优势倾向</h2>${rep.strengths.map(s=>`<section><h3>${s.title}</h3><p>${s.body}</p></section>`).join('')}<h2>可以留意的另一面</h2>${rep.blindSpots.map(s=>`<section><h3>${s.title}</h3><p>${s.body}</p></section>`).join('')}<section><h2>${rep.work.title}</h2><p>${rep.work.body}</p></section><section><h2>${rep.relationships.title}</h2><p>${rep.relationships.body}</p></section><h2>7 日成长计划</h2>${rep.growthPlan.map(d=>`<section><h3>${(rr.growthDone||[]).includes(d.day)?'✓':'○'} DAY ${d.day} · ${d.title}</h3><p>${d.body}</p></section>`).join('')}<hr><small>根据本轮选择与预设内容规则生成，未经心理测量验证。不构成心理诊断或专业建议。题量增加不等同于更高的准确度。人格是坐标，不是边界。</small></body></html>`;saveBlob(new Blob([html],{type:'text/html;charset=utf-8'}),`INNER-SPACE-${r.type}-报告.html`);toast('完整报告已导出。打开文件可打印或保存 PDF。');}
app.addEventListener('click',e=>{const b=e.target.closest('button,a.brand');if(!b)return;
 if(b.classList.contains('brand')){e.preventDefault();go('home');return;}
 if(b.dataset.tier){tierId=b.dataset.tier;store.selectTier(tierId);loadDraft();render();document.querySelector(`[data-tier="${tierId}"]`).focus({preventScroll:true});chime();return;}
 if(b.dataset.island!==undefined){activeIsland=Number(b.dataset.island);world?.select(activeIsland);renderCards();toast(`${names[activeIsland]} · ${subs[activeIsland]}`);return;}
 if(b.dataset.option!==undefined){selected=Number(b.dataset.option);chime();document.querySelectorAll('.option').forEach((o,i)=>{o.classList.toggle('chosen',i===selected);o.setAttribute('aria-pressed',String(i===selected));o.querySelector('.option-check').innerHTML=i===selected?icons.check:icons.up;});document.querySelector('[data-action=next]').disabled=false;return;}
 if(b.dataset.record){showReport('insights',b.dataset.record);return;}
 if(b.dataset.delete){modal(`<span class="overline">LOCAL RECORD</span><h2>删除这份档案？</h2><p>这份测评及其成长打卡会从本机移除，其他记录和未完成进度不受影响。</p><div class="modal-actions"><button class="primary" data-confirm-delete="${b.dataset.delete}">删除档案</button><button class="secondary" data-action="close">保留</button></div>`);return;}
 if(b.dataset.confirmDelete){store.deleteRecord(b.dataset.confirmDelete);if(record?.id===b.dataset.confirmDelete)record=null;document.querySelector('#dialog').close();renderHistory();toast('这份档案已删除。');return;}
 if(b.dataset.reportTab){reportTab=b.dataset.reportTab;renderReport();document.querySelector(`[data-report-tab="${reportTab}"]`).focus({preventScroll:true});return;}
 if(b.dataset.growth){const day=Number(b.dataset.growth),offset=scrollY;if(record.id==='demo'){record.growthDone=record.growthDone.includes(day)?record.growthDone.filter(d=>d!==day):[...record.growthDone,day];}else{store.toggleGrowth(record.id,day);record=currentRecord();}renderReport();window.scrollTo({top:offset,behavior:'instant'});document.querySelector(`[data-growth="${day}"]`).focus({preventScroll:true});chime(640);return;}
 if(b.dataset.type){const r=getProfile(b.dataset.type);modal(`<button class="text-button" data-action="atlas">${icons.back} 全部人格</button><div class="atlas-detail-type">${r.type}</div><h2>${r.name}</h2><p>${r.description}</p><div class="tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><p class="modal-note">${r.tagline}</p>`);return;}
 if(b.id==='sound'){sound=!sound;b.innerHTML=sound?icons.sound:icons.mute;b.setAttribute('aria-pressed',String(sound));b.setAttribute('aria-label',sound?'关闭音效':'开启音效');chime();return;}
 switch(b.dataset.action){
  case 'start':start();break;
  case 'home':go('home');break;
  case 'exit':saveDraft();go('home');break;
  case 'next':{if(selected===null)return;answers[index]=items()[index].options[selected].value;chime(680);world?.celebrate();if(index===items().length-1){record=store.complete(tierId,answers);screen='result';if(!store.available)toast('本次结果仅在当前页面保留，请导出报告。');}else{index++;selected=answers[index]===undefined?null:items()[index].options.findIndex(o=>o.value===answers[index]);saveDraft();if(index%(items().length/4)===0)toast(`新区域已解锁 · ${names[Math.floor(index/(items().length/4))]}`);}render();focusContent();if(innerWidth<800)scrollTop();break;}
  case 'back':if(index>0){index--;selected=items()[index].options.findIndex(o=>o.value===answers[index]);saveDraft();render();focusContent();}break;
  case 'restart':go('home');break;
  case 'download':downloadCard();break;
  case 'export-report':exportReport();break;
  case 'report':showReport();break;
  case 'growth':showReport('growth');break;
  case 'history':go('history');break;
  case 'pro':pro();break;
  case 'pro-report':document.querySelector('#dialog').close();showReport();break;
  case 'guide':guide();break;
  case 'atlas':atlas();break;
  case 'close':document.querySelector('#dialog').close();break;
  case 'begin-from-modal':document.querySelector('#dialog').close();start();break;
  case 'motion':reduced=!reduced;world?.setReducedMotion(reduced);b.textContent=reduced?'▷':'Ⅱ';b.setAttribute('aria-label',reduced?'播放场景动画':'暂停场景动画');break;
 }
});
app.addEventListener('change',e=>{if(e.target.matches('[data-compare]')){comparisonIds[Number(e.target.dataset.compare)]=e.target.value;renderHistory();document.querySelector(`[data-compare="${e.target.dataset.compare}"]`)?.focus({preventScroll:true});}});
document.querySelector('#dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}});
loadDraft();render();
if(import.meta.env.DEV)window.__INNER_SPACE__={diagnostics:()=>world?.getDiagnostics(),getState:()=>({screen,tierId,index,answers:[...answers],accessMode:access.mode})};
