import './playground.css';
import { characterTypes,getCharacterInfo } from './characters.js';
import {mountCharacterViewer,populatePortraits} from './character-viewer.js';
import {newAdventure,getAdventureNode,chooseAdventure,canChooseAdventure,adventureSummary,adventureNodes,endings} from './adventure.js';
import {duoDecks,duoQuestions,newDuo,beginDuoTurn,answerDuo,nextDuoRound,duoSummary} from './duo.js';
import {createPlayStore} from './play-store.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const portrait=t=>`<img class="character-portrait" data-portrait="${t}" alt="${t} ${getCharacterInfo(t).role}" width="360" height="400">`;
const typeOptions=type=>characterTypes.map(t=>`<option value="${t}" ${type===t?'selected':''}>${t} · ${getCharacterInfo(t).role}</option>`).join('');
export function createPlayground(container,{chime=()=>{},getReduced=()=>false,getType=()=> 'ENFP'}={}){
 const store=createPlayStore({getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)});
 let view='hub',story=store.snapshot().current,feedback=null,duo=null,deck='daily',selectedTypes=['ENFP','INTJ'],storyType='ENFP',draft={self:null,prediction:null},viewer=null,confirm=null;
 const dispose=()=>{viewer?.dispose();viewer=null;};
 function show(mode){if(mode==='adventure'){storyType=getType();view='story-setup';}else if(mode==='duo'){selectedTypes=[getType(),'INTJ'];view='duo-setup';}render();}
 function header(kicker,title,description){return `<div class="play-heading"><div><span class="overline">${kicker}</span><h1 class="page-title" tabindex="-1">${title}</h1><p>${description}</p></div>${view!=='hub'?'<button class="secondary" data-play="hub">返回游戏厅</button>':''}</div>`;}
 function collection(){const owned=store.snapshot().collection;return `<section class="ending-shelf"><div class="shelf-heading"><h2>夜航纪念章</h2><span>${owned.length} / ${endings.length} 已收集</span></div><div class="ending-grid">${endings.map((e,i)=>`<div class="ending-stamp ${owned.includes(e.id)?'owned':''}"><span>${owned.includes(e.id)?'✦':'◇'}</span><b>${owned.includes(e.id)?e.title:`未发现结局 ${i+1}`}</b><small>${owned.includes(e.id)?'已收入本机收藏':'走另一条路，再见一面'}</small></div>`).join('')}</div></section>`;}
 function hub(){return header('PLAY / DISCOVER / CONNECT','人格之外，继续开玩。','一个人改写故事，两个人交换脑洞。两种新玩法，都从一次选择开始。')+`<div class="play-mode-grid"><button class="play-mode-card night" data-play="adventure"><span class="mode-kicker">01 / SOLO STORY</span><div class="play-card-art">${portrait('ENFP')}<span class="mode-orbit">✦</span></div><div><span class="play-pill">单人 · 约 3–5 分钟</span><h2>霓虹夜航</h2><p>流星雨就要来了。带着有限电量出发，收集信号、结识伙伴，决定今夜的结局。</p><b>分支故事 · 4 个结局 · 自动存档 <span>↗</span></b></div></button><button class="play-mode-card together" data-play="duo"><span class="mode-kicker">02 / TWO MINDS</span><div class="play-card-art pair">${portrait('INTP')}${portrait('ESFP')}</div><div><span class="play-pill">双人同机 · 每局 6 回合</span><h2>双人默契挑战</h2><p>你会怎么选？朋友又会怎么选？把手机传过去，一起揭晓意料之外的答案。</p><b>3 个题包 · 轮流作答 · 揭晓聊天 <span>↗</span></b></div></button></div>${duo?'<button class="secondary resume-duo" data-play="duo-resume">继续这局双人挑战</button>':''}${collection()}<p class="play-note">游戏选择独立于人格测试。角色只代表你选用的形象，游戏得分不会修改 MBTI 结果。</p>`;}
 function storySetup(){return header('NEON NIGHT / BRANCHING ADVENTURE','霓虹夜航','带着有限电量赶赴流星雨，为自己和沿途伙伴找到值得记住的结尾。')+`<div class="play-setup"><div class="setup-art">${portrait(storyType)}<span>你的夜航形象</span></div><div><span class="play-pill">六次决定，一段自己的故事</span><h2>这一次，走哪条路？</h2><p>每一步都会改变电量、信号或同行关系。看清成本，利用沿路物品，在终点选择一个满足条件的结局。</p><label class="play-field">选择出发形象<select data-play-select="story-type">${typeOptions(storyType)}</select></label><p class="play-note">形象不影响资源、难度或可获得的结局。</p><div class="play-buttons">${story?`<button class="primary" data-play="story-resume">${story.status==='complete'?'回看上次结局':'继续上次夜航'}</button>`:''}<button class="${story?'secondary':'primary'}" data-play="story-start">开启新夜航 ↗</button></div>${story?.status==='playing'?'<p class="play-note">新夜航会替换未完成进度，已收集纪念章会保留。</p>':''}</div></div>${collection()}`;}
 const meters=()=>`<div class="story-meters" aria-label="当前资源"><div><span>⚡ 电量</span><b>${story.energy}</b></div><div><span>⌁ 信号</span><b>${story.signal}</b></div><div><span>♡ 同行</span><b>${story.bond}</b></div></div>`;
 function journal(){return `<details class="story-journal"><summary>路线日志 · ${story.path.length} 次选择</summary><ol>${story.path.map(p=>{const node=adventureNodes[p.node];return `<li><b>${esc(node.title)}</b><span>${esc(node.options[p.choice].text)}</span></li>`;}).join('')}</ol></details>`;}
 function storyScreen(){
  const completed=story.status==='complete'&&!feedback,node=completed?null:getAdventureNode(story),ending=completed?adventureSummary(story):null;
  const speaker=feedback?.speakerType||node?.speakerType||story.type;
  return header('NEON NIGHT / YOUR JOURNEY',completed?'今夜，由你点亮。':feedback?'选择，正在改变故事。':node?.scene||'霓虹夜航',completed?'每条路都有自己的回响。把这一枚纪念章留给今天。':'目标：抵达发射台，选择属于你的流星雨结局。')+`<div class="story-progress" aria-label="已完成 ${story.path.length} 次选择，共 6 次">${Array.from({length:6},(_,i)=>`<span class="${i<story.path.length?'done':''}">${i+1}</span>`).join('')}</div>${meters()}<div class="story-layout"><div class="story-stage" data-scene="${esc(node?.id||'ending')}"><span class="scene-caption">${completed?'NIGHT COMPLETE':esc(feedback?.scene||node?.scene||'夜航')}</span><div class="play-live-character" data-live-type="${speaker}"></div><span class="speaker-tag">${speaker} / ${getCharacterInfo(speaker).role}</span><button class="story-motion" data-play="motion">${getReduced()?'静态模式':'和 TA 打个招呼'}</button></div><section class="story-content" aria-live="polite">${feedback?`<span class="overline">CHOICE ECHO / 选择回响</span><h2 tabindex="-1">${esc(feedback.text)}</h2><p>${esc(feedback.feedback)}</p><div class="choice-delta">${esc(feedback.delta)}</div><button class="primary" data-play="story-continue">${story.status==='complete'?'揭晓结局':'继续夜航'} →</button>`:completed?`<span class="ending-emblem">✦</span><span class="overline">ENDING UNLOCKED</span><h2 tabindex="-1">${esc(ending.title)}</h2><p>${esc(ending.description)}</p><p class="ending-highlight">${esc(ending.highlight||'已收入夜航纪念章')}</p><div class="play-buttons"><button class="primary" data-play="adventure">再走一条路 ↗</button><button class="secondary" data-play="duo">邀请身边的人玩</button></div>`:`<span class="overline">ENCOUNTER ${String(story.path.length+1).padStart(2,'0')} / 06</span><h2 tabindex="-1">${esc(node.title)}</h2><p>${esc(node.description)}</p><div class="story-choices">${node.options.map((o,i)=>{const gate=canChooseAdventure(story,i);return `<button class="story-choice" data-story-choice="${i}" ${gate.allowed?'':'disabled'}><b><span>${String.fromCharCode(65+i)}</span>${esc(o.text)}</b><small>${esc(o.hint)}${gate.allowed?'':` · ${esc(gate.reason)}`}</small></button>`;}).join('')}</div>`}</section></div><div class="story-inventory"><span>随身物品</span>${story.items.length?story.items.map(i=>`<b>${esc(i)}</b>`).join(''):'<small>沿路发现的物品会留在这里</small>'}</div>${journal()}${completed?collection():''}<p class="play-note">${store.available?'夜航进度自动保存在本机。':'当前浏览器无法保存进度，请保持页面打开。'} 退出后可从游戏厅继续。</p>`;
 }
 function duoSetup(){return header('TWO MINDS / ONE SCREEN','双人默契挑战','找一个身边的人。两个人，一台手机；先保密，再一起揭晓。')+`<div class="duo-instructions"><span>01 各选自己的答案</span><i>→</i><span>02 猜对方怎么选</span><i>→</i><span>03 一起揭晓、聊一句</span></div><div class="duo-decks">${duoDecks.map(d=>`<button data-duo-deck="${d.id}" class="${deck===d.id?'selected':''}" aria-pressed="${deck===d.id}"><b>${d.name}</b><span>${d.description}</span><small>6 回合 · 3 个选项</small></button>`).join('')}</div><div class="duo-cast">${selectedTypes.map((t,i)=>`<label class="play-field"><span>玩家 ${i?'B':'A'} 的形象</span><div class="duo-avatar">${portrait(t)}</div><select data-play-select="duo-${i}">${typeOptions(t)}</select></label>`).join('')}</div><div class="play-buttons"><button class="primary" data-play="duo-start">${duo?'重开一局（替换当前局）':'我们准备好了'} ↗</button>${duo?'<button class="secondary" data-play="duo-resume">继续当前局</button>':''}</div><p class="play-note">这是同机互动，不是线上匹配。答案只在当前页面保留，刷新会清空；不会影响测评结果。</p>`;}
 function scoreline(summary){return `<div class="duo-scores"><div><b>${summary.shared}<small> / ${summary.rounds}</small></b><span>同选时刻</span></div><div><b>${summary.correctA}<small> / ${summary.rounds}</small></b><span>A 猜中 B</span></div><div><b>${summary.correctB}<small> / ${summary.rounds}</small></b><span>B 猜中 A</span></div></div>`;}
 function roundReveal(row,index){const q=duoQuestions[duo.deckId][index];return `<article class="duo-reveal-row"><span class="overline">ROUND ${index+1} / ${row.match?'SAME WAVELENGTH':'NEW PERSPECTIVE'}</span><h3>${esc(q.title)}</h3><div class="reveal-pair">${[row.a,row.b].map((a,i)=>`<div><b>玩家 ${i?'B':'A'}</b><p>${esc(q.options[a.self])}</p><small>预测对方：${esc(q.options[a.prediction])}</small><em>${(i?row.correctB:row.correctA)?'✓ 这次猜中了':'↗ 发现一个新侧面'}</em></div>`).join('')}</div><p class="talk-prompt">聊一句：${esc(q.talk)}</p></article>`;}
 function duoScreen(){const q=duoQuestions[duo.deckId][duo.round],who=duo.player?'B':'A',other=duo.player?'A':'B',summary=duoSummary(duo);
  const head=header(`TWO MINDS / ${duoDecks.find(d=>d.id===duo.deckId).name}`,duo.phase==='complete'?'原来，你是这样的你。':`第 ${duo.round+1} / 6 回合`,duo.phase==='complete'?'相同是惊喜，不同是话题。这些分数只来自本局实际选择。':'先选自己，再猜对方。揭晓后，说说你为什么这样选。');
  if(duo.phase==='handoff')return head+`<div class="handoff-curtain"><span class="handoff-lock">◇</span><span class="overline">PRIVATE TURN / 请先交接设备</span><h2 tabindex="-1">请把手机交给玩家 ${who}</h2><p>${duo.player?'A 的答案已收好，现在由 B 独立作答。':'另一位玩家请先转过身，给答案留一点悬念。'}</p><button class="primary" data-play="duo-ready">我是玩家 ${who}，开始作答 →</button><small>交接时不展示本题或任何已提交答案</small></div>`;
  if(duo.phase==='answer')return head+`<div class="duo-answer"><div class="turn-badge">玩家 ${who} 的回合 <span>请独立作答</span></div><h2 tabindex="-1">${esc(q.title)}</h2>${['self','prediction'].map(key=>`<fieldset><legend>${key==='self'?'① 你自己会选什么？':`② 猜玩家 ${other} 会选什么？`}</legend><div class="duo-options">${q.options.map((o,i)=>`<button data-duo-answer="${key}" data-choice="${i}" aria-pressed="${draft[key]===i}" class="${draft[key]===i?'selected':''}"><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div></fieldset>`).join('')}<button class="primary" data-play="duo-submit" ${draft.self===null||draft.prediction===null?'disabled':''}>${duo.player?'锁定答案，一起揭晓':'锁定答案，交给 B'} →</button></div>`;
  if(duo.phase==='reveal')return head+scoreline(summary)+roundReveal(summary.rows.at(-1),duo.round)+`<div class="play-buttons"><button class="primary" data-play="duo-next">${duo.round===5?'查看整局回顾':'下一回合'} →</button></div>`;
  return head+scoreline(summary)+`<div class="duo-finale"><div>${portrait(duo.types[0])}</div><span>×</span><div>${portrait(duo.types[1])}</div></div><p class="play-note">${summary.shared===6?'这一局每题都选到一起！可以换个题包，看看别的情境。':summary.shared===0?'这一局每题都看到不同视角，试着从一个意外答案聊起。':'相同与不同，都让你们多认识了彼此一点。'} 不是人格兼容度或关系预测。</p><div class="play-buttons"><button class="primary" data-play="duo">换个题包再来 ↗</button><button class="secondary" data-play="hub">返回游戏厅</button></div><details class="duo-review"><summary>回顾全部 6 个情境</summary>${summary.rows.map((r,i)=>roundReveal(r,i)).join('')}</details>`;
 }
 function render(){dispose();container.innerHTML=view==='hub'?hub():view==='story-setup'?storySetup():view==='story'?storyScreen():view==='duo-setup'?duoSetup():duoScreen();
  if(confirm)container.insertAdjacentHTML('afterbegin',`<div class="play-confirm" role="alert"><p>${confirm==='story'?'替换未完成的夜航？收藏会保留。':'结束当前双人局并重新开始？'}</p><button class="primary" data-play="confirm-start">确认重开</button><button class="secondary" data-play="cancel-start">保留当前局</button></div>`);
  populatePortraits(container);const stage=container.querySelector('[data-live-type]');if(stage)try{viewer=mountCharacterViewer(stage,stage.dataset.liveType,{reducedMotion:getReduced()});if(feedback||story?.status==='complete')viewer.celebrate();}catch{stage.innerHTML=portrait(stage.dataset.liveType);populatePortraits(stage);}
 }
 function update({top=true}={}){render();if(top)window.scrollTo({top:0,behavior:'instant'});container.querySelector('h2[tabindex],.page-title')?.focus({preventScroll:true});}
 function startStory(){story=newAdventure(storyType);store.save(story);feedback=null;view='story';}
 function startDuo(){duo=newDuo(deck,selectedTypes);draft={self:null,prediction:null};view='duo';}
 container.addEventListener('change',e=>{const key=e.target.dataset.playSelect;if(key==='story-type')storyType=e.target.value;else if(key?.startsWith('duo-'))selectedTypes[Number(key.at(-1))]=e.target.value;else return;const value=e.target.value;render();const select=container.querySelector(`[data-play-select="${key}"]`);select.value=value;select.focus({preventScroll:true});});
 container.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
  if(b.dataset.storyChoice!==undefined&&view==='story'&&!feedback&&story.status==='playing'){
   const i=Number(b.dataset.storyChoice),node=getAdventureNode(story),o=node.options[i],before=story;story=chooseAdventure(story,i);store.save(story);const labels={energy:'电量',signal:'信号',bond:'同行'};feedback={...o,scene:node.scene,speakerType:node.speakerType,delta:Object.keys(labels).map(k=>{const d=story[k]-before[k];return d?`${labels[k]} ${d>0?'+':''}${d}`:'';}).filter(Boolean).join(' · ')||'资源保持不变'};chime(680);update();return;
  }
  if(b.dataset.duoDeck){deck=b.dataset.duoDeck;render();container.querySelector(`[data-duo-deck="${deck}"]`).focus({preventScroll:true});return;}
  if(b.dataset.duoAnswer&&duo?.phase==='answer'){draft[b.dataset.duoAnswer]=Number(b.dataset.choice);const offset=scrollY;render();window.scrollTo({top:offset,behavior:'instant'});container.querySelector(`[data-duo-answer="${b.dataset.duoAnswer}"][data-choice="${b.dataset.choice}"]`).focus({preventScroll:true});chime();return;}
  switch(b.dataset.play){
   case 'hub':if(duo?.phase==='answer'){duo={...duo,phase:'handoff'};draft={self:null,prediction:null};}view='hub';feedback=null;confirm=null;break;
   case 'adventure':storyType=getType();view='story-setup';break;
   case 'duo':view='duo-setup';break;
   case 'story-start':if(story?.status==='playing')confirm='story';else startStory();break;
   case 'story-resume':view='story';feedback=null;break;
   case 'story-continue':feedback=null;break;
   case 'duo-start':if(duo&&duo.phase!=='complete')confirm='duo';else startDuo();break;
   case 'confirm-start':if(confirm==='story')startStory();else if(confirm==='duo')startDuo();confirm=null;break;
   case 'cancel-start':confirm=null;break;
   case 'duo-resume':view='duo';break;
   case 'duo-ready':duo=beginDuoTurn(duo);draft={self:null,prediction:null};break;
   case 'duo-submit':if(draft.self===null||draft.prediction===null)return;duo=answerDuo(duo,draft);draft={self:null,prediction:null};chime(duo.phase==='reveal'?720:480);break;
   case 'duo-next':duo=nextDuoRound(duo);break;
   case 'motion':viewer?.celebrate();return;
   default:return;
  }update();
 });
 return {render,show,leave(){dispose();if(duo?.phase==='answer'){duo={...duo,phase:'handoff'};draft={self:null,prediction:null};}confirm=null;},setReducedMotion(value){viewer?.setReducedMotion(value);},diagnostics:()=>viewer?.getDiagnostics()};
}
